- name: Allow connections on multiple ports
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_ports:
      - "22"
      - "80"
      - "443"
      - "8080"
      - "3000"
      - "8000:9999"
    jump: ACCEPT

- name: Allow related and established connections
  ansible.builtin.iptables:
    chain: INPUT
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT
  become: yes

#- name: Block DROP
#  ansible.builtin.iptables:
#    chain: INPUT
#    policy: DROP
#  become: true